pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src\Microsoft.Security.Utilities.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(solution)
    arguments: '--configuration $(buildConfiguration) --no-restore'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: $(solution)
    arguments: '--collect "Code coverage" --no-build --configuration $(buildConfiguration)'
